[package]
name = "bevy_stylebox"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"

[features]
basis-universal = ["bevy/basis-universal"]
